# Site settings
title: "Merciless Simplification Methodology"
description: "Systematic methodology for reducing codebase complexity by 20-40% while maintaining 100% functionality"
baseurl: "/merciless-simplification"
url: "https://mfenderov.github.io"
author: "Mark Fenderov"

# Jekyll settings
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Show downloads button
show_downloads: false

# SEO and social
twitter:
  username: mfenderov
  card: summary_large_image

# Build settings
safe: true
incremental: false

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Include files
include:
  - _pages